name: Rust

on:
  push:
    branches: 
      - "*"
      - "**"
  pull_request_target:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run validity tests
      run: cargo test validity --verbose
